name: build
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: git clone ${{ secrets.DOCKER_REPO }} .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Display Go version
        run: go version

      - name: Generate Binaries
        run: |
          CGO_ENABLED=0 GOOS=linux go build -mod=readonly -o bin/denv && \
          CGO_ENABLED=0 GOOS=darwin go build -mod=readonly -o bin/denv-darwin && \
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -mod=readonly -o bin/denv-arm64

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: 1
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          asset_paths: '["./bin/denv*"]'