name: build
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: git clone ${{ secrets.DOCKER_REPO }} .

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          platforms: linux/amd64,linux/arm64
          name: denv
          dest: dist

      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        with:
          args: ./dist/*
